config/routes.rb
Tweeter::Application.routes.draw do

  devise_for :users

  resources :follows

  resources :tweets
  resources :followings

  resources :users
  root :to => 'tweets#index'
  match 'following/:id/:follow_user_id'=> 'following#create', :as=>:create
  match 'followings/new/:follow_user_id'=>'followings#create',  :as=>:create
  match 'following/'=>'followings#index'
  match 'following/:id'=>'followings#index'

  devise_for :users,  :class_name => 'User'
  devise_scope :user do
    root :to=> "devise/registrations#new"
  end

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  validates_length_of :text, :maximum => 140
  validates :text, :presence => true


end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # GET /tweets
  # GET /tweets.json
  before_filter :get_tweet, :only => [:edit, :update, :destroy]
  before_filter :check_login, :only =>[:edit,:update,:destroy]




  def get_tweet
    @tweet = Tweet.find(params[:id])
  end

  def check_login
    if @tweet.user.id != current_user.id
      flash[:notice] ="Sorry you do not have access to complete this action"
      redirect_to tweets_path
    end
  end
  def index
    @tweets = Tweet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tweets }
    end
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/new
  # GET /tweets/new.json
  def new
    if !user_signed_in?
      redirect_to(new_user_session_path)
      return
    end
    @tweet = Tweet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(params[:tweet])
    @tweet.time = DateTime.now
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render json: @tweet, status: :created, location: @tweet }
      else
        format.html { render action: "new" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tweets/1
  # PUT /tweets/1.json
  def update
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      if @tweet.update_attributes(params[:tweet])
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url }
      format.json { head :ok }
    end
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper

   def check_login
     if user_signed_in?
       if current_user.id = user_id
         return true
       end
     end
     return false
   end
end

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id  %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h1>Listing tweets</h1>

  <%= render '/tweets/display/display_tweet_table' %>

<% @tweets.each do |tweet| %>
      <% @tweet=tweet %>
 <%= render '/tweets/display/displayTweets'%>
<% end %>
</table>

<br />

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= link_to @tweet.user.username, @tweet.user %>
</p>

<p>
  <b>Time:</b>
  <%= (@tweet.created_at - DateTime.now).abs.to_i %>
</p>

<p>
  <b>Text:</b>
  <%= @tweet.text %>
</p>
<p>
  <%= link_to 'Follow', new_following_url()+"/"+@tweet.user_id.to_s%>
</p>
<% if user_signed_in? %>
<%if current_user.id == @tweet.user.id %>
<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%end%>
<%end%>
<%= link_to 'Back', tweets_path %>