config/routes.rb
Tweeter::Application.routes.draw do

  devise_for :users

  resources :follows

  resources :tweets
  resources :followings

  resources :users
  root :to => 'tweets#index'
  match 'following/:id/:follow_user_id'=> 'following#create', :as=>:create
  match 'followings/new/:follow_user_id'=>'followings#create',  :as=>:create
  match 'following/'=>'followings#index'
  match 'following/:id'=>'followings#index'

  devise_for :users,  :class_name => 'User'
  devise_scope :user do
    root :to=> "devise/registrations#new"
  end

end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :user
  has_one :user, :through =>:user_id
  has_one :user, :through=> :follow_user_id
  attr_accessible :user_id
  attr_accessible :follow_user_id
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController

  # GET /follows
  # GET /follows.json
  def index
    @follows = Follow.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @follows }
    end
  end

  # GET /follows/1
  # GET /follows/1.json
  def show
    @follow = Follow.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @follow }
    end
  end

  # GET /follows/new
  # GET /follows/new.json
  def new
    if !user_signed_in?
      session[:return_to] = new_follow_path
      redirect_to(new_user_session_path)
      return
    end
    @follow = Follow.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @follow }
    end
  end

  # GET /follows/1/edit
  def edit
    @follow = Follow.find(params[:id])
  end

  # POST /follows
  # POST /follows.json
  def create

    @follow = Follow.new()
    if user_signed_in?
      @follow = Follow.new
      @follow.user_id = current_user.id
      @follow.follow_user_id =params[:follow_user_id]
    else
      redirect_to new_user_session_path
    end

    respond_to do |format|
      if @follow.save
        format.html { redirect_to @follow, notice: 'Follow was successfully created.' }
        format.json { render json: @follow, status: :created, location: @follow }
      else
        format.html { render action: "new" }
        format.json { render json: @follow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /follows/1
  # PUT /follows/1.json
  def update
    @follow = Follow.find(params[:id])

    respond_to do |format|
      if @follow.update_attributes(params[:follow])
        format.html { redirect_to @follow, notice: 'Follow was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @follow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /follows/1
  # DELETE /follows/1.json
  def destroy
    @follow = Follow.find(params[:id])
    @follow.destroy

    respond_to do |format|
      format.html { redirect_to follows_url }
      format.json { head :ok }
    end
  end
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/views/follows/_form.html.erb
<%= semantic_form_for @follow do |f| %>
  <%= f.inputs do %>
    <%= f.input :user_id %>
    <%= f.input :follow_user_id %>
  <% end %>

  <%= f.buttons do %>
    <%= f.commit_button %>
  <% end %>
<% end %>

app/views/follows/edit.html.erb
<h1>Editing follow</h1>

<%= render 'form' %>

<%= link_to 'Show', @follow %> |
<%= link_to 'Back', follows_path %>

app/views/follows/index.html.erb
<h1>Listing follows</h1>

<table>
  <tr>
    <th>User</th>
    <th>Follow user</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @follows.each do |follow| %>
  <tr>
    <td><%= follow.user_id %></td>
    <td><%= follow.follow_user_id %></td>
    <td><%= link_to 'Show', follow %></td>
    <td><%= link_to 'Edit', edit_follow_path(follow) %></td>
    <td><%= link_to 'Destroy', follow, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Follow', new_follow_path %>

app/views/follows/new.html.erb
<h1>New follow</h1>

<%= render 'form' %>

<%= link_to 'Back', follows_path %>

app/views/follows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @follow.user_id %>
</p>

<p>
  <b>Follow user:</b>
  <%= @follow.follow_user_id %>
</p>


<%= link_to 'Edit', edit_follow_path(@follow) %> |
<%= link_to 'Back', follows_path %>